# 패키지 설치

In [ ]:
!pip install torch torchvision torchaudio

In [3]:
import torch

# 1. 텐서 만들기
- torch.tensor : np.array()같은거

### - 0차원 텐서=스칼라값

In [49]:
torch.tensor(32)

tensor(32)

### - 1차원 텐서=벡터

In [44]:
t1 = torch.tensor([0., 1., 2., 3., 4., 5., 6.]) # float32
t2 = torch.tensor([0,1,2,3,4,5,6]) # int64
t3 = torch.tensor([0,1,2,3,4,5,6],dtype=torch.float32) # float으로 변환
print(t1,t2,t3)

print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape이랑 동일

tensor([0., 1., 2., 3., 4., 5., 6.]) tensor([0, 1, 2, 3, 4, 5, 6]) tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


### 인덱싱, 슬라이싱 가능

In [8]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### - 2차원 텐서=행렬

In [45]:
t = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.],
                  [7., 8., 9.],
                  [10., 11., 12.]])
print(t)
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])


### 인덱싱 슬라이싱 -> 넘파이랑 동일

In [18]:
t[[0,1],[0,1]] #각 각 하나씩만

tensor([1., 5.])

In [20]:
t[[0,1]][:,[0,1]] # 이렇게하면 R처럼 가져올수있음

tensor([[1., 2.],
        [4., 5.]])

In [22]:
t[1,[1,2]] # 아니면 한쪽이 하나만

tensor([5., 6.])

In [24]:
t[:,[1,2]] #아니면 최소 한쪽이 ':'일떄

tensor([[ 2.,  3.],
        [ 5.,  6.],
        [ 8.,  9.],
        [11., 12.]])

## - 다양한 텐서 만드는 방법들

In [57]:
torch.arange(start=1, end=9, step=1).reshape(2,4) # np.arange

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [59]:
torch.linspace(start=0, end=10, steps=12).reshape(3,4) # np.linspace

tensor([[ 0.0000,  0.9091,  1.8182,  2.7273],
        [ 3.6364,  4.5455,  5.4545,  6.3636],
        [ 7.2727,  8.1818,  9.0909, 10.0000]])

In [60]:
torch.zeros(size=(3,2,1))

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]])

In [61]:
torch.ones(size=(1,2,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [62]:
torch.full(size=(2,3), fill_value=7) # value로 전부 채우기

tensor([[7, 7, 7],
        [7, 7, 7]])

### - 넘파이 값을 넣어도 됌

In [81]:
import numpy as np
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.tensor(t)
ft

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]], dtype=torch.int32)

# 2. 브로드 캐스팅

### 같은 크기 연산

In [46]:
m1 = torch.tensor([[3, 3]])
m2 = torch.tensor([[2, 4]])
m1 + m2 # 같은 위치끼리

tensor([[5, 7]])

### 같은 차원이라도 shape다르면 하나가 1이어야함 !!!

In [55]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.tensor([[1, 2]])
m2 = torch.tensor([[3], [4]])
print(m1+m2) # (1,2)+(2, -> [1,2]+[3,3]  -> (2,2)로
             #        1)    [1,2] [4,4]

tensor([[4, 5],
        [5, 6]])


### 다른 차원 연산
- shape해서 각 차원끼리 비교했을때 서로 같거나 하나가 1이어야함!!!!!  
ex) (2, 3, 4)+(3, 1) 가능
- (2,3,4)
- (1,3,1)

In [51]:
# matrix + vector(scalar도 가능)
m1 = torch.tensor([[1, 2]])
m2 = torch.tensor([3]) # [3]을 -> [3, 3]로 변형
m1 + m2   #  

tensor([[4, 5]])

In [52]:
# 3차원텐서 + 행렬 
m1 = torch.tensor([[[1, 2],[1, 2],[1, 2]],[[1, 2],[1, 2],[1, 2]]]) # (2,3,2)
m2 = torch.tensor([[3,5]]) # (1,2)
m1+m2   # (2,3,2)+(1,1,2)라서 가능 -> (2,3,2)로

tensor([[[4, 7],
         [4, 7],
         [4, 7]],

        [[4, 7],
         [4, 7],
         [4, 7]]])

# 3. 여러 기능들

In [70]:
m1 = torch.tensor([[1, 2], [3, 4]]) # (2,2)
m2 = torch.tensor([[1], [2]])  # (2,1)
m3=m1*m2

### 사칙연산
- shape이 같거나 하나가 1이면 가능 !!!

In [71]:
torch.add(m1, m2)       # m1.mul(m2) 도 가능
torch.sub(m1, m2)       # m1.sub(m2)
torch.mul(m1, m2)       # m1.mul(m2)
torch.div(m1, m2)       # m1.div(m2)

tensor([[1.0000, 2.0000],
        [1.5000, 2.0000]])

### 행렬곱

In [72]:
torch.matmul(m1,m2), m1.matmul(m2), m1@m2 #전부 가능

(tensor([[ 5],
         [11]]),
 tensor([[ 5],
         [11]]),
 tensor([[ 5],
         [11]]))

### 집계함수
- dim옵션이 axis의 역할(numpy에서의 축과 동일)
- sum, mean, max, min, std, var, argmax등

In [75]:
m3

tensor([[1, 2],
        [6, 8]])

In [76]:
m3.sum() # 전부

tensor(17)

In [77]:
m3.sum(dim=0) # 밑으로(행끼리)

tensor([ 7, 10])

In [78]:
m3.sum(dim=1) # 옆으로(열끼리)

tensor([ 3, 14])

In [79]:
m3.sum(dim=-1) # 마지막 축 기준으로

tensor([ 3, 14])

# 4. 모양변경, 합치기

In [83]:
t = torch.tensor([[[0, 1, 2],
                   [3, 4, 5]],
                  [[6, 7, 8],
                   [9, 10, 11]]])
t.shape

torch.Size([2, 2, 3])

### reshape

In [84]:
t.reshape(2,1,6) # 넘파이처럼 reshape하면 됨

tensor([[[ 0,  1,  2,  3,  4,  5]],

        [[ 6,  7,  8,  9, 10, 11]]])

In [85]:
t.reshape(-1,4) # 차원 축소도 가능, -1이면 남는 만큼을 할당

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### squeeze: 1인 차원으로 제거

In [87]:
sq=t.reshape(2,1,6)
sq.squeeze().shape

torch.Size([2, 6])

### unsqueeze: 1인 차원으로 추가

In [88]:
uns=t.unsqueeze(dim=0) # n번째 차원에 1인 차원으로 추가
uns.shape

torch.Size([1, 2, 2, 3])

### cat: 텐서붙이기

In [89]:
x = torch.tensor([[1, 2], [3, 4]]) # (2,2)
y = torch.tensor([[5, 6], [7, 8]]) # (2,2)

In [95]:
torch.cat([x,y],dim=0) #(4,2)  첫번째 차원 늘리기-> 행방향인 밑으로

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [96]:
torch.cat([x,y],dim=1) #(2,4) 두번째 차원으로 늘리기 -> 열방향인 옆으로

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

### stack: 새로운 차원 생성하면서 붙이기
- n차원간의 stack이면 dim은 0부터 n까지 존재

In [102]:
s1=torch.stack([x,y],dim=0) # 가장 바깥 차원에 새 축 추가 → x, y가 위아래로 쌓임
s1.shape, s1

(torch.Size([2, 2, 2]),
 tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]))

In [103]:
s2=torch.stack([x,y],dim=1) #  두 번째 축에 쌓음 → 각 행마다 x, y의 행을 묶음
s2.shape, s2

(torch.Size([2, 2, 2]),
 tensor([[[1, 2],
          [5, 6]],
 
         [[3, 4],
          [7, 8]]]))

In [104]:
s3=torch.stack([x,y],dim=2) # 세 번째 축에 쌓음 → 각 원소 위치별로 x와 y를 함께 묶음
s3.shape, s3

(torch.Size([2, 2, 2]),
 tensor([[[1, 5],
          [2, 6]],
 
         [[3, 7],
          [4, 8]]]))